DROP DATABASE IF EXISTS coffee;
CREATE DATABASE coffee CHARSET = UTF8;
USE coffee;
CREATE TABLE user(
 uId    INT PRIMARY KEY AUTO_INCREMENT,
 uName VARCHAR(30) NOT NULL,
 uPassword VARCHAR(30) NOT NULL,
 uSex ENUM('0','1','2') NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET = UTF8;

INSERT INTO user VALUES(null,'lucy','123456','1 ');
INSERT INTO user VALUES(null,'jerry','123456','0 ');
INSERT INTO user VALUES(null,'lily','123456','1 ');
